[package]
name = "burroughs_wheeler_transformation"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
chrono = { workspace = true }
tracing-subscriber = { workspace = true }
rdxsort = { workspace = true }
itertools = "0.14.0"
voracious_radix_sort = "1.2.0"
rand = { workspace = true }
utils = { workspace = true }
