[workspace]
name = "binary_data_encoding_algorithms"
version = "0.1.0"
edition = "2024"
members = [
    "base64lab"
]
resolver = "2"

[profile.test]
    inherits = "release"
    overflow-checks = true

[workspace.dependencies]
thiserror = "2.0.16"
base64 = "0.22.1"
text_io = { version = "0.1.13" }





